import "./test-utils.js"
import "./test-vecxyz.js"
import "./test-hull.js"
import "./test-overlap.js"
import "./test-affine.js"
import "./test-proximity.js"
import "./test-parser.js"
import "./test-rgbcolor.js"